### ISSUE TITLE
Values with ampersand break parseParams

### ISSUE THREAD

**Issue by cshold** [nathamanath/URI.js#2]
Hey, solid plugin. Parameters that have ampersands in them — eg. `category=Big%20&%20Tall` in the URL — cause `Cannot read property 'match' of undefined` from `valueType`'s first `match` conditional.

Looks like the root cause is `params = search.split('&');` in `parseParams`, as it doesn't take into account any other possible ampersands.

**Comment by nathamanath** [comment]
Hi, sorry for the slow response on this I completely missed the notification email!

Interesting, I guess to achieve this we would split the search string based on a regex... So split only on ampersands which are followed by an ampersand-free string and then an equals.

Thanks for the bug report :) Ill have a look at it

**Comment by nathamanath** [comment]
hows that? https://github.com/nathamanath/URI.js/commit/8aa26aea25171faad1db7b9d92e0ad8df3b41255

**Comment by cshold** [comment]
I'm no regex master, but that looks pretty good

**Comment by nathamanath** [comment]
woo! Thanks again for pointing that out :)
